name: I.S.D.I CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-install-cache

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Run tests
        run: flutter test --coverage

      # Example build step for production. Requires secure key properties set up in GitHub Secrets.
      # - name: Build production APK
      #   if: github.ref == 'refs/heads/main'
      #   run: flutter build apk --release --flavor prod --dart-define=FLAVOR=prod
      
      # - name: Upload Artifact
      #   if: github.ref == 'refs/heads/main'
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: release-apk
      #     path: build/app/outputs/flutter-apk/app-prod-release.apk
